### PR TITLE
Product type2

### PR DESCRIPTION
**Pull request by farrellkat**
ticket: https://github.com/nss-day-cohort-30/bangazon-api-punctual-puffins/issues/3

Run the master database builder in Azure. 
Run each test in TestProductTypes and make sure they all succeed. 

URL: http://localhost:5000/api/producttype

use this url in Postman and make sure you can successfully get all, get one ID between 1-5, create a new object by putting 
```
{
"name": "Toaster"
}
```
in the body. Delete that toaster.

### CODE REVIEW

**Review by prafullatass — CHANGES_REQUESTED** [review]
Test failed - Test_Get_One_False_ProductType()
Also would like to add the same test on Delete and Put Methods.

**Comment by Ryan-Nelson** [comment]
All of your test pass on my machine 
read me need tweking

**Review by prafullatass — APPROVED** [review]
The code is working. And all tests are positive

**Review by Ryan-Nelson — APPROVED** [review]

**Comment by trevanyoung** [comment]
Solid

**Pull request merged**
